config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborations
    collection do
      get :all
    end
  end

  resources :charges, only: [:new, :create]
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

  

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :role, inclusion: { in: %w{standard admin premium} }
  has_many :wikis
  has_many :collaborations
  has_many :collab_wikis, through: :collaborations, source: :wiki
  
  def role
    self[:role] ||= 'standard'
  end

  def role?(r)
    self[:role] == r
  end

  def premium?
    role == 'premium' || role == 'admin'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations # eg subscriptions
  has_many :collaborators, through: :collaborations, source: :user # eg has many subscribers through subscriptions

  validates :title, presence: true
  default_scope { order('created_at DESC') }
  #scope :public_only, -> { where( private: nil) }
  scope :public_only, -> { where private: [nil, false] }
  scope :private_only, -> { where private: true }

  def public?
    !private?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError do |exception|
      redirect_to root_url, alert: exception.message
    end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def create
  @amount = 1500 #Amount in cents

  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: @amount,
    description: "Premium Membership #{current_user.email}",
    currency: 'usd'
    )

  current_user.role = "premium"
  current_user.save
  
  flash[:notice] = "Thank you for upgrading to a premium Blocipedia account!"
  #redirect_to user_path(current_user)
  redirect_to wikis_path

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to wikis_path
end

def new
  @amount = 1500

  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Premium Membership #{current_user.email}",
    amount: @amount
  }
end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  def index
    @users = User.all
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators = @wiki.collaborators
  end

  def new
  end

  def create
    @wiki = Wiki.find params[:wiki_id]
    @user = User.find params[:user_id]
    @wiki.collaborations.create user: @user
    flash[:notice] = "Collaborator Added" 
    redirect_to action: :index
  end

  def destroy
    @wiki = Wiki.find params[:wiki_id]
    collaboration = @wiki.collaborations.find params[:id]
    # collaboration = Collaboration.find params[:id] 
    if collaboration.destroy 
      flash[:notice] = "Collaborator removed"
    else
      flash[:error] = "Collaborator could not be removed"
    end
    redirect_to action: :index
  end
 
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to wikis_path
    end
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def all
    @whose = 'All'
    @wikis = Wiki.public_only
    authorize @wikis
    render :index
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(params.require(:wiki).permit(:title, :body, :private))
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki entry was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the entry. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.destroy
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<h4>Click here to upgrade</h4>
<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description=="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborations/index.html.erb
<h1>Collaborators</h1>

<ul>
<% @users.each do |user| %>
  <li>
    <%= user.email %>
    <% if @wiki.collaborators.include? user %>
      <% collaboration = @wiki.collaborations.find_by_user_id( user.id) %>
      <%= link_to "Remove", wiki_collaboration_path(@wiki, collaboration), method: :delete %> 
    <% else %>
      <%= link_to "Add", wiki_collaborations_path(@wiki, user_id: user.id), method: :post %>
    <% end %> 

  </li>
  
  <% end %>
</ul>
<%= link_to "Back to Wiki", wiki_path(@wiki), class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.email %>! 
          <%= link_to "Edit Profile", edit_user_registration_path %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">

    <h1>Blocipedia</h1>
    <p>Welocme to Blocipedia! Blocipedia will allow you to create public and <em>private</em> Markdown-based wikis. With a premium account, you can even host your own private wikis and add unlimited collaborators to them.  Sign up for a standard (free) or premium account today!</p>
    <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
    </p>
     <p><small>After signing up, you can upgrade your account to a Premium Account or change your account details by visiting the "Edit Profile" link at the top of your screen.</small></p>
  </div>

</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 16, class: 'form-control', placeholder: "Enter Wiki text" %>
      </div>

      <% if current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
 
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @topic } %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1><%= @whose %> Wikis</h1>

<% if policy(Wiki.new).create? %>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <p><%= link_to wiki.title, wiki %></p>
  <small>
    submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %><br/>
  </small>
<% end %>

app/views/wikis/new.html.erb
<h1>Create a New Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown @wiki.title %></h1>
<p><%= markdown @wiki.body %></p>

<% if policy(@wiki).edit? %>
  <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<% if @wiki.private? %>
  <p><strong>PRIVATE</strong></p>
<% end %>

<% if current_user == @wiki.user %>
  <%= link_to "Manage Collaborators", wiki_collaborations_path(@wiki), class: 'btn btn-success' %>
<% end %> 

<% if policy(@wiki).destroy? %>
  <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this data?' } %>
<% end %>